### Importing python libraries

In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

### Location to save figures

In [2]:
# Where to save the figures
PROJECT_ROOT_DIR = "."
IMAGES_PATH = PROJECT_ROOT_DIR

def save_fig(fig_id, tight_layout=True, fig_extension="pdf", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
#     if tight_layout:
#         plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution,
                bbox_inches="tight", pad_inches=0,)

### Loading the dataset to the Pandas Dataframe

In [3]:
df_target = pd.read_csv("csvs/DBP_SBP.csv")
df_features = pd.read_csv("csvs/Full_features.csv")

In [4]:
df_features

1         2         3  4         5         6         7  \
0       2.917889  2.890518  1.152493  1  0.990620  0.009380  0.394975   
1       2.808407  2.730205  1.121212  1  0.972155  0.027845  0.399234   
2       2.989247  2.869990  1.142717  1  0.960105  0.039895  0.382276   
3       2.990225  2.894428  1.159335  1  0.967963  0.032037  0.387708   
4       2.772239  2.722385  1.031281  1  0.982017  0.017983  0.372003   
...          ...       ...       ... ..       ...       ...       ...   
140811  2.884653  2.042033  1.029326  1  0.707896  0.292104  0.356828   
140812  3.039101  2.533724  1.540567  1  0.833709  0.166291  0.506915   
140813  3.381232  2.694037  2.601173  1  0.796762  0.203238  0.769297   
140814  3.109482  2.888563  1.476051  1  0.928953  0.071047  0.474693   
140815  2.924731  2.527859  0.940371  1  0.864305  0.135695  0.321524   

               8      9     10  ...        55        56        57        58  \
0       0.595645  0.368  0.240  ...  2.086334  2.468231  2.829326  2.877419   
1       0.572920  0.368  0.240  ...  1.940450  2.294233  2.690127  2.733333   
2       0.577829  0.336  0.208  ...  2.049306  2.418377  2.841838  2.907527   
3       0.580255  0.280  0.152  ...  2.089619  2.481916  2.854350  2.906940   
4       0.610014  0.248  0.120  ...  1.894115  2.258065  2.671945  2.716325   
...          ...    ...    ...  ...       ...       ...       ...       ...   
140811  0.351067  0.416  0.216  ...  1.954565  2.174976  2.723363  2.837928   
140812  0.326793  0.208  0.480  ...  2.322346  2.471163  2.863734  2.988074   
140813  0.027465  0.248  0.440  ...  2.667527  2.714565  3.229521  3.340958   
140814  0.454260  0.192  0.032  ...  2.086022  2.496579  2.892082  3.034800   
140815  0.542781  0.400  0.128  ...  1.929384  2.312805  2.668426  2.854545   

              59        60        61        62        63          64  
0       1.637341  1.864743  0.601830  0.362200  1.864743  233.092864  
1       1.581623  1.773388  0.565174  0.319422  1.773388  221.673509  
2       1.627566  1.861474  0.609525  0.371521  1.861474  232.684262  
3       1.642229  1.874628  0.619411  0.383670  1.874628  234.328446  
4       1.499511  1.718850  0.582576  0.339395  1.718850  214.856305  
...          ...       ...       ...       ...       ...         ...  
140811  1.551320  1.748113  0.586742  0.344266  1.748113  218.514174  
140812  1.926686  2.022053  0.550055  0.302560  2.022053  252.756598  
140813  2.521017  2.383546  0.586180  0.343607  2.383546  297.943304  
140814  1.487781  1.815500  0.703564  0.495002  1.815500  226.937439  
140815  1.396872  1.693357  0.638398  0.407552  1.693357  211.669599  

[140816 rows x 64 columns]

In [5]:
df_target

DBP         SBP
0       67.307176  124.601310
1       65.597632  120.986846
2       67.062955  122.745234
3       68.088681  125.187439
4       68.723655  124.112869
...           ...         ...
140811  64.229997  108.726976
140812  60.859754  103.500657
140813  84.842209  120.107652
140814  57.440667  106.724368
140815  65.060347  105.942862

[140816 rows x 2 columns]

In [6]:
df_features.describe()

1              2              3         4              5  \
count  140816.000000  140816.000000  140816.000000  140816.0  140816.000000   
mean        2.850740       2.821881       1.172309       1.0       0.993183   
std         0.216135       0.225517       0.237364       0.0       0.086342   
min         2.000000       2.000000       0.000000       1.0       0.509665   
25%         2.739980       2.706745       1.033236       1.0       0.956770   
50%         2.874878       2.852395       1.121212       1.0       0.993514   
75%         2.974585       2.958944       1.262952       1.0       1.026124   
max         4.001955       4.001955       3.871945       1.0       1.980976   

                   6              7              8              9  \
count  140816.000000  140816.000000  140816.000000  140816.000000   
mean        0.006817       0.413331       0.579853       0.265015   
std         0.086342       0.091573       0.117783       0.107891   
min        -0.980976       0.000000      -0.475208       0.016000   
25%        -0.026124       0.359694       0.524057       0.200000   
50%         0.006486       0.390235       0.600329       0.264000   
75%         0.043230       0.445432       0.649913       0.336000   
max         0.490335       1.058745       1.786993       0.936000   

                  10  ...             55             56             57  \
count  140816.000000  ...  140816.000000  140816.000000  140816.000000   
mean        0.167037  ...       2.134681       2.423520       2.764516   
std         0.130157  ...       0.224563       0.202497       0.186480   
min         0.016000  ...       1.089541       1.330401       1.775171   
25%         0.072000  ...       1.987175       2.297165       2.661388   
50%         0.136000  ...       2.133998       2.431085       2.779668   
75%         0.224000  ...       2.278397       2.553275       2.872727   
max         0.888000  ...       3.454663       3.760508       4.001955   

                  58             59             60             61  \
count  140816.000000  140816.000000  140816.000000  140816.000000   
mean        2.853238       1.714578       1.871631       0.592568   
std         0.191314       0.218720       0.159022       0.087784   
min         1.938416       0.778104       1.077443       0.052775   
25%         2.750538       1.565005       1.772096       0.542058   
50%         2.866667       1.694037       1.859597       0.603866   
75%         2.951124       1.845552       1.956442       0.652506   
max         4.001955       3.138807       3.202526       1.631027   

                  62             63             64  
count  140816.000000  140816.000000  140816.000000  
mean        0.358842       1.871631     233.953905  
std         0.102795       0.159022      19.877737  
min         0.002785       1.077443     134.680352  
25%         0.293827       1.772096     221.511975  
50%         0.364654       1.859597     232.449658  
75%         0.425764       1.956442     244.555230  
max         2.660250       3.202526     400.315738  

[8 rows x 61 columns]

In [7]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140816 entries, 0 to 140815
Data columns (total 64 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   1       140816 non-null  float64
 1   2       140816 non-null  float64
 2   3       140816 non-null  float64
 3   4       140816 non-null  int64  
 4   5       140816 non-null  float64
 5   6       140816 non-null  float64
 6   7       140816 non-null  float64
 7   8       140816 non-null  float64
 8   9       140816 non-null  float64
 9   10      140816 non-null  float64
 10  11      140816 non-null  float64
 11  12      140816 non-null  float64
 12  13      140816 non-null  float64
 13  14      140816 non-null  float64
 14  15      140816 non-null  float64
 15  16      140816 non-null  float64
 16  17      140816 non-null  float64
 17  18      140816 non-null  float64
 18  19      140816 non-null  float64
 19  20      140816 non-null  float64
 20  21      140816 non-null  float64
 21  22      14

In [8]:
X_train = df_features.drop(["25","26","27","49"],axis=1)
X_train
X_train = X_train.to_numpy()
X_train

array([[  2.91788856,   2.89051808,   1.15249267, ...,   0.36219967,
          1.86474291, 233.0928641 ],
       [  2.80840665,   2.73020528,   1.12121212, ...,   0.31942169,
          1.77338807, 221.6735093 ],
       [  2.98924731,   2.86999023,   1.1427175 , ...,   0.37152082,
          1.8614741 , 232.684262  ],
       ...,
       [  3.38123167,   2.69403715,   2.60117302, ...,   0.34360702,
          2.38354643, 297.943304  ],
       [  3.10948192,   2.88856305,   1.47605083, ...,   0.49500248,
          1.81549951, 226.9374389 ],
       [  2.92473118,   2.52785924,   0.94037146, ...,   0.40755222,
          1.69335679, 211.6695992 ]])

In [9]:
y_train = df_target.drop(['DBP'], axis=1)
y_train

SBP
0       124.601310
1       120.986846
2       122.745234
3       125.187439
4       124.112869
...            ...
140811  108.726976
140812  103.500657
140813  120.107652
140814  106.724368
140815  105.942862

[140816 rows x 1 columns]

### Create y_train (sparse numbers)

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
#     le.fit(df_train_dir_cat.values.flatten())
#     le.classes_
y_train = le.fit_transform(y_train.values.flatten())
n_classes = len(le.classes_)

In [11]:
le.classes_

array([ 53.7773588 ,  55.15470866,  55.43805835, ..., 199.28375075,
       199.63542796, 199.9284923 ])

In [12]:
unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

[[    0     1]
 [    1     1]
 [    2     1]
 ...
 [10964     2]
 [10965     1]
 [10966     1]]


### Create an evaluation func for cross validation

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

def create_model(model_type):
    if model_type == 'knn':
        model = KNeighborsRegressor(weights='distance', n_neighbors=4)
    elif model_type == 'lin_reg':
        model = LinearRegression()
    elif model_type == 'svr':
        model = SVR(kernel="poly")
    elif model_type == 'rf':
        model = RandomForestRegressor(n_estimators=100,random_state=430) # 32,200,400,430 
    elif model_type == 'dtree':
        model = DecisionTreeRegressor(splitter='random',random_state=430) # 34, 
    return model

### Create an evaluation func for cross validation

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.metrics import r2_score
import time

#%run ../utils/print_cm

def func_cv(model_type, X_train, y_train, cv_itr, n_cv):
    ix = 0
    
    for train_ix, test_ix in cv_itr.split(X_train, y_train):
    #     print(X_train[train_ix].shape, y_train[train_ix].shape)
        x_tr, y_tr = X_train[train_ix], y_train[train_ix]
        x_ts, y_ts = X_train[test_ix], y_train[test_ix]

        model = create_model(model_type)
        model.fit(x_tr, y_tr)
        y_pred = model.predict(x_ts)
        
        print('\n\n')
        print(time.strftime('%X %x %Z'))
        print('{0}-cv confusion matrix'.format(ix))
        print('')
        
        mae = mean_absolute_error(y_ts, y_pred)
        mse = mean_squared_error(y_ts, y_pred)
        rmse = np.sqrt(mean_squared_error(y_ts, y_pred))
        var = r2_score(y_ts, y_pred)
        
        print('MAE: \t {0:.5f}'.format(mae))
        print('MSE: \t {0:.5f}'.format(mse))
        print('RMSE:\t {0:.5f}'.format(rmse))

        print('-'* 80)
        ix = ix + 1
        
    print('Aggregated confusion matrix')
   # print_cm(cm_agg, le.classes_)
    print('')
    print('Aggregated avg MAE:\t {0:.5f}'.format(np.mean(mae)))
    print('Aggregated avg MSE:\t {0:.5f}'.format(np.mean(mse)))
    print('Aggregated avg RMSE:\t {0:.5f}'.format(np.mean(rmse)))

### Create k-fold index set for cross validation¶
**Kfold, StratifiedKfold, or StratifiedShuffleSplit**

In [15]:
from sklearn.model_selection import StratifiedKFold, KFold

n_cross_valid = 10
kf = KFold(n_splits=n_cross_valid, shuffle=True, random_state=33)
# for unbalanced data sets,
# skf = StratifiedKFold(n_splits=n_cv, shuffle=False, random_state=33) 
# sss = StratifiedShuffleSplit(n_splits=n_cv, test_size=0.25, random_state=33)

### Run cross validation

In [16]:
import sys
import time

org_stdout = sys.stdout
f = open('DBP_result' + '.txt', 'w')
sys.stdout = f

model_types = ['knn',
              'lin_reg',
               'svr',
               'rf',
               'dtree']

for model_type in model_types:
    print('\n')
    print('*'*80)
    print('*'*80)
    print(model_type)
    print(time.strftime('%X %x %Z'))
    print('*'*80)
    print('*'*80)
    func_cv(model_type, X_train, y_train, kf, n_cross_valid)
    
f.close()
# sys.stdout.close()
sys.stdout = org_stdout